import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Sample TITLE",
  description: "Generated by create next app",
};

export default function SubLayout({ children }: LayoutProps<"/pomodoro">) {
  return <div className="min-h-full flex flex-col">{children}</div>;
}

