import type { Metadata } from "next";
import "@/app/globals.css";
import { FlashcardProvider } from "@/context/FlashcardContext";

export const metadata: Metadata = {
  title: "Sample TITLE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <FlashcardProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </FlashcardProvider>
    </html>
  );
}
